### ISSUE TITLE
How to use this script?

### ISSUE THREAD

**Issue by owen800q** [sherdeadlock/maple-block#1]
How can I inject this script into maple.bilibili.to?

**Comment by owen800q** [comment]
Load the script with TamperMonkey but still not working

**Comment by sherdeadlock** [comment]
Load the extension in Developer mode. You can get started by the tutorial.
https://developer.chrome.com/extensions/getstarted#manifest

**Comment by owen800q** [comment]
> Load the extension in Developer mode. You can get started by the tutorial.
> https://developer.chrome.com/extensions/getstarted#manifest

Thanks, it works perfectly
